import { chmod, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, expect, it } from 'vitest';

import { checkCodexSchema, CliHarness, defineWorkflow, runWorkflow, z } from '../src/index.js';
import { prepareCodexSchema } from '../src/harnesses/codex-schema.js';
import { jsonValue } from '../src/workflow/runtime/json.js';
import { schemaMatrix } from './schema-matrix.js';

const directories: string[] = [];
const jsonSchema = (schema: z.ZodType): ReturnType<typeof jsonValue> =>
  jsonValue(JSON.parse(JSON.stringify(z.toJSONSchema(schema, { target: 'draft-7' }))));

async function binaryFor(
  value: unknown,
): Promise<{ directory: string; binary: string; marker: string }> {
  const directory = await mkdtemp(join(tmpdir(), 'quiet-choir-schema-test-'));
  directories.push(directory);
  const binary = join(directory, 'codex');
  const marker = join(directory, 'spawned');
  const events = [
    { type: 'item.completed', item: { type: 'agent_message', text: JSON.stringify(value) } },
    { type: 'turn.completed' },
  ]
    .map((event) => JSON.stringify(event))
    .join('\n');
  await writeFile(
    binary,
    `#!${process.execPath}\nconst fs = require('node:fs'); fs.writeFileSync(${JSON.stringify(marker)}, 'yes'); const args = process.argv.slice(2); fs.copyFileSync(args[args.indexOf('--output-schema') + 1], ${JSON.stringify(join(directory, 'wire.json'))}); process.stdout.write(${JSON.stringify(events)});`,
  );
  await chmod(binary, 0o700);
  return { directory, binary, marker };
}

afterEach(async () => {
  await Promise.all(
    directories.splice(0).map(async (directory) => rm(directory, { recursive: true, force: true })),
  );
});

it('pins the schema matrix to output generated by the locked Zod version', async () => {
  const fixture: unknown = JSON.parse(
    await readFile(new URL('./fixtures/codex-schema-matrix.json', import.meta.url), 'utf8'),
  );
  expect(fixture).toEqual({
    zodVersion: '4.5.4',
    cases: schemaMatrix.map(({ name, schema, output, rules }) => ({
      name,
      schema: jsonSchema(schema),
      output,
      rules,
    })),
  });
});

it.each(schemaMatrix)(
  'lints the observed $name schema and round-trips its compatibility encoding',
  ({ schema, rules, wire, output }) => {
    const issues = checkCodexSchema(schema);
    expect([...new Set(issues.map((issue) => issue.rule))]).toEqual(rules);
    expect(issues.every((issue) => issue.path.startsWith('$') && issue.fix.length > 0)).toBe(true);
    expect(checkCodexSchema(jsonSchema(schema))).toEqual(issues);
    if (rules.some((rule) => rule === 'tuple')) {
      expect(() => prepareCodexSchema(jsonSchema(schema), 'compat')).toThrow('$.pair (tuple)');
      return;
    }
    const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
    expect(checkCodexSchema(plan.schema)).toEqual([]);
    const decoded: unknown = JSON.parse(plan.decode(JSON.stringify(wire)));
    expect(decoded).toEqual(output);
    expect(schema.safeParse(decoded).success).toBe(true);
  },
);

it.each(schemaMatrix.filter((entry) => entry.rules.length > 0))(
  'rejects $name in strict mode before spawning',
  async ({ schema }) => {
    const { binary, marker } = await binaryFor({});
    await expect(
      new CliHarness({ codexBinary: binary }).invoke(
        {
          provider: 'codex',
          cwd: process.cwd(),
          options: { prompt: 'fixture', structuredOutput: 'strict' },
          outputSchema: jsonSchema(schema),
        },
        new AbortController().signal,
      ),
    ).rejects.toThrow('Codex strict mode rejects this output schema:');
    await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  },
);

it.each(schemaMatrix.filter((entry) => entry.name !== 'tuple'))(
  'executes and validates $name through the default compat adapter',
  async ({ schema, wire, output }) => {
    const { binary, directory } = await binaryFor(wire);
    const resultSchema: z.ZodType = schema;
    const workflow = defineWorkflow({
      name: 'schema',
      version: '1',
      input: z.null(),
      output: resultSchema,
      async run(ctx) {
        return (await ctx.codex.object('answer', { prompt: 'fixture', schema: resultSchema }))
          .output;
      },
    });
    const result = await runWorkflow(workflow, {
      runId: 'schema',
      stateDir: directory,
      input: null,
      harness: new CliHarness({ codexBinary: binary }),
    });
    expect(result.output).toEqual(schema.parse(output));
    expect(
      checkCodexSchema(jsonValue(JSON.parse(await readFile(join(directory, 'wire.json'), 'utf8')))),
    ).toEqual([]);
  },
);

it('retains nullable optionals and strips null only from non-nullable optionals inside unions and records', () => {
  const schema = z.object({
    data: z.record(
      z.string(),
      z.discriminatedUnion('kind', [
        z.object({ kind: z.literal('a'), a: z.number().optional() }),
        z.object({ kind: z.literal('b'), b: z.string().nullable().optional() }),
      ]),
    ),
  });
  const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
  const decoded: unknown = JSON.parse(
    plan.decode(
      '{"data":[{"key":"x","value":{"kind":"b","b":null}},{"key":"y","value":{"kind":"a","a":null}}]}',
    ),
  );
  expect(decoded).toEqual({ data: { x: { kind: 'b', b: null }, y: { kind: 'a' } } });
  expect(schema.safeParse(decoded).success).toBe(true);
});

it('supports shared and recursive local schema references', () => {
  const schema = {
    type: 'object',
    properties: { next: { anyOf: [{ $ref: '#' }, { type: 'null' }] }, name: { type: 'string' } },
    required: ['next'],
    additionalProperties: false,
  };
  expect(checkCodexSchema(schema).map((issue) => issue.path)).toEqual(['$.name']);
  const plan = prepareCodexSchema(schema, 'compat');
  expect(checkCodexSchema(plan.schema)).toEqual([]);
  expect(JSON.parse(plan.decode('{"next":{"next":null,"name":"child"},"name":null}'))).toEqual({
    next: { next: null, name: 'child' },
  });
  const shared = {
    type: 'object',
    properties: { 'odd/key': { $ref: '#/definitions/a~1b' } },
    required: ['odd/key'],
    additionalProperties: false,
    definitions: {
      'a/b': {
        type: 'object',
        properties: { value: { type: 'string' } },
        additionalProperties: false,
      },
    },
  };
  expect(checkCodexSchema(shared)[0]?.path).toBe('$["odd/key"].value');
  expect(
    JSON.parse(prepareCodexSchema(shared, 'compat').decode('{"odd/key":{"value":null}}')),
  ).toEqual({ 'odd/key': {} });
});

it('rejects invalid compatibility output instead of silently corrupting values', () => {
  const recordPlan = prepareCodexSchema(jsonSchema(z.record(z.string(), z.number())), 'compat');
  expect(() => recordPlan.decode('{}')).toThrow('missing value');
  expect(() => recordPlan.decode('{"value":{}}')).toThrow('array of key/value');
  expect(() => recordPlan.decode('{"value":[{}]}')).toThrow('requires key and value');
  expect(() =>
    recordPlan.decode('{"value":[{"key":"x","value":1},{"key":"x","value":2}]}'),
  ).toThrow('duplicate keys');
  const decoded: unknown = JSON.parse(
    recordPlan.decode('{"value":[{"key":"__proto__","value":1}]}'),
  );
  expect(Object.getPrototypeOf(decoded)).toBe(Object.prototype);
  expect(Object.hasOwn(decoded as object, '__proto__')).toBe(true);
  expect(() =>
    prepareCodexSchema(jsonSchema(z.array(z.string())), 'compat').decode('{"value":null}'),
  ).toThrow('must be an array');
  expect(() => prepareCodexSchema(jsonSchema(z.object({})), 'compat').decode('null')).toThrow(
    'must be an object',
  );
  expect(() =>
    prepareCodexSchema(
      jsonSchema(z.union([z.object({ a: z.string() }), z.object({ b: z.number() })])),
      'compat',
    ).decode('{"value":{}}'),
  ).toThrow('did not match any');
});

it('preserves original validation and refuses tuples in compatibility mode before spawning', async () => {
  const { binary, directory, marker } = await binaryFor({ value: 'x' });
  await expect(
    new CliHarness({ codexBinary: binary }).invoke(
      {
        provider: 'codex',
        cwd: process.cwd(),
        options: { prompt: 'fixture' },
        outputSchema: jsonSchema(z.tuple([z.string()])),
      },
      new AbortController().signal,
    ),
  ).rejects.toThrow('(tuple)');
  await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  const schema = z.object({ value: z.string().refine((value) => value.length > 3, 'too short') });
  const workflow = defineWorkflow({
    name: 'refinement',
    version: '1',
    input: z.null(),
    output: schema,
    async run(ctx) {
      return (await ctx.codex.object('answer', { prompt: 'fixture', schema })).output;
    },
  });
  await expect(
    runWorkflow(workflow, {
      runId: 'refine',
      stateDir: directory,
      input: null,
      harness: new CliHarness({ codexBinary: binary }),
    }),
  ).rejects.toThrow('too short');
});

it('does not mutate the supplied schema and leaves strict native schemas unchanged', () => {
  const schema = jsonSchema(z.object({ name: z.string() }));
  const copy = structuredClone(schema);
  const strict = prepareCodexSchema(schema, 'strict');
  expect(strict.schema).toEqual(schema);
  expect(strict.decode('original bytes')).toBe('original bytes');
  prepareCodexSchema(schema, 'compat');
  expect(schema).toEqual(copy);
  expect(() => checkCodexSchema({ $ref: 'https://example.test/schema' })).toThrow('external');
  expect(() => checkCodexSchema({ $ref: '#/definitions/missing' })).toThrow('Unresolved');
  expect(() => checkCodexSchema({ $ref: '#' })).toThrow('Cyclic schema reference');
  expect(
    checkCodexSchema({
      $ref: '#/anyOf/0',
      anyOf: [{ type: 'object', properties: {}, required: [], additionalProperties: false }],
    }),
  ).toEqual([]);
  const described = prepareCodexSchema(
    jsonSchema(z.record(z.string(), z.string()).describe('Labels by ID')),
    'compat',
  );
  expect(described.schema).toMatchObject({
    properties: { value: { description: 'Labels by ID' } },
  });
});

it.each(['discriminated-union', 'array-root', 'string-root'])(
  'rejects the observed Claude %s root before spawning',
  async (name) => {
    const entry = schemaMatrix.find((entry) => entry.name === name);
    if (!entry) throw new Error('Missing matrix entry');
    const { binary, marker } = await binaryFor({});
    await expect(
      new CliHarness({ claudeBinary: binary }).invoke(
        {
          provider: 'claude',
          cwd: process.cwd(),
          options: { prompt: 'fixture' },
          outputSchema: jsonSchema(entry.schema),
        },
        new AbortController().signal,
      ),
    ).rejects.toThrow('Claude structured output requires an object root at $');
    await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  },
);

it.each(
  schemaMatrix.filter(
    (entry) => !['discriminated-union', 'array-root', 'string-root'].includes(entry.name),
  ),
)('keeps the original $name schema for Claude', async ({ schema, output }) => {
  const { binary, directory } = await binaryFor({});
  const schemaPath = join(directory, 'claude-schema.json');
  await writeFile(
    binary,
    `#!${process.execPath}\nconst fs = require('node:fs'); const args = process.argv.slice(2); fs.writeFileSync(${JSON.stringify(schemaPath)}, args[args.indexOf('--json-schema') + 1]); console.log(${JSON.stringify(JSON.stringify({ type: 'result', subtype: 'success', structured_output: output }))});`,
  );
  const response = await new CliHarness({ claudeBinary: binary }).invoke(
    {
      provider: 'claude',
      cwd: process.cwd(),
      options: { prompt: 'fixture' },
      outputSchema: jsonSchema(schema),
    },
    new AbortController().signal,
  );
  expect(JSON.parse(await readFile(schemaPath, 'utf8'))).toEqual(jsonSchema(schema));
  expect(schema.safeParse(JSON.parse(response.text)).success).toBe(true);
});
