import { testInvocation } from './harness-invocation.js';
import { chmod, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, expect, it } from 'vitest';

import { checkCodexSchema, CliHarness, defineWorkflow, runWorkflow, z } from '../src/index.js';
import { prepareCodexSchema } from '../src/harnesses/codex-schema.js';
import { jsonValue } from '../src/workflow/runtime/json.js';
import { schemaMatrix } from './schema-matrix.js';

const compatRejectedRules = ['tuple', 'untyped'];
const isCompatRejected = (entry: { rules: readonly string[] }): boolean =>
  entry.rules.some((rule) => compatRejectedRules.includes(rule));
const untypedEntries = schemaMatrix.filter((entry) =>
  (entry.rules as readonly string[]).includes('untyped'),
);
const directories: string[] = [];
const jsonSchema = (schema: z.ZodType): ReturnType<typeof jsonValue> =>
  jsonValue(JSON.parse(JSON.stringify(z.toJSONSchema(schema, { target: 'draft-7' }))));

async function binaryFor(
  value: unknown,
): Promise<{ directory: string; binary: string; marker: string }> {
  const directory = await mkdtemp(join(tmpdir(), 'quiet-choir-schema-test-'));
  directories.push(directory);
  const binary = join(directory, 'codex');
  const marker = join(directory, 'spawned');
  const events = [
    { type: 'item.completed', item: { type: 'agent_message', text: JSON.stringify(value) } },
    { type: 'turn.completed' },
  ]
    .map((event) => JSON.stringify(event))
    .join('\n');
  await writeFile(
    binary,
    `#!${process.execPath}\nconst fs = require('node:fs'); fs.writeFileSync(${JSON.stringify(marker)}, 'yes'); const args = process.argv.slice(2); fs.copyFileSync(args[args.indexOf('--output-schema') + 1], ${JSON.stringify(join(directory, 'wire.json'))}); process.stdout.write(${JSON.stringify(events)});`,
  );
  await chmod(binary, 0o700);
  return { directory, binary, marker };
}

afterEach(async () => {
  await Promise.all(
    directories.splice(0).map(async (directory) => rm(directory, { recursive: true, force: true })),
  );
});

it('pins the schema matrix to output generated by the locked Zod version', async () => {
  const fixture: unknown = JSON.parse(
    await readFile(new URL('./fixtures/codex-schema-matrix.json', import.meta.url), 'utf8'),
  );
  expect(fixture).toEqual({
    zodVersion: '4.5.4',
    cases: schemaMatrix.map(({ name, schema, output, rules }) => ({
      name,
      schema: jsonSchema(schema),
      output,
      rules,
    })),
  });
});

it.each(schemaMatrix)(
  'lints the observed $name schema and round-trips its compatibility encoding',
  ({ schema, rules, wire, output }) => {
    const issues = checkCodexSchema(schema);
    expect([...new Set(issues.map((issue) => issue.rule))]).toEqual(rules);
    expect(issues.every((issue) => issue.path.startsWith('$') && issue.fix.length > 0)).toBe(true);
    expect(checkCodexSchema(jsonSchema(schema))).toEqual(issues);
    const rejected = issues.find((issue) => compatRejectedRules.includes(issue.rule));
    if (rejected) {
      expect(() => prepareCodexSchema(jsonSchema(schema), 'compat')).toThrow(
        `${rejected.path} (${rejected.rule})`,
      );
      return;
    }
    const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
    expect(checkCodexSchema(plan.schema)).toEqual([]);
    const decoded: unknown = JSON.parse(plan.decode(JSON.stringify(wire)));
    expect(decoded).toEqual(output);
    expect(schema.safeParse(decoded).success).toBe(true);
  },
);

it.each(schemaMatrix.filter((entry) => entry.rules.length > 0))(
  'rejects $name in strict mode before spawning',
  async ({ schema }) => {
    const { binary, marker } = await binaryFor({});
    await expect(
      new CliHarness({ codexBinary: binary }).invoke(
        {
          harness: 'codex',
          cwd: process.cwd(),
          options: { prompt: 'fixture', structuredOutput: 'strict' },
          outputSchema: jsonSchema(schema),
        },
        testInvocation(new AbortController().signal),
      ),
    ).rejects.toThrow('Codex rejects this output schema (structuredOutput: "strict"):');
    await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  },
);

it.each(schemaMatrix.filter((entry) => !isCompatRejected(entry)))(
  'executes and validates $name through the default compat adapter',
  async ({ schema, wire, output }) => {
    const { binary, directory } = await binaryFor(wire);
    const resultSchema: z.ZodType = schema;
    const workflow = defineWorkflow({
      name: 'schema',
      version: '1',
      input: z.null(),
      output: resultSchema,
      async run(ctx) {
        return (await ctx.codex.object('answer', { prompt: 'fixture', schema: resultSchema }))
          .output;
      },
    });
    const result = await runWorkflow(workflow, {
      runId: 'schema',
      stateDir: directory,
      input: null,
      harness: new CliHarness({ codexBinary: binary }),
    });
    expect(result.output).toEqual(schema.parse(output));
    expect(
      checkCodexSchema(jsonValue(JSON.parse(await readFile(join(directory, 'wire.json'), 'utf8')))),
    ).toEqual([]);
  },
);

it.each(untypedEntries)('rejects $name before spawning in both modes', async ({ schema }) => {
  for (const structuredOutput of ['compat', 'strict'] as const) {
    const { binary, marker } = await binaryFor({});
    await expect(
      new CliHarness({ codexBinary: binary }).invoke(
        {
          harness: 'codex',
          cwd: process.cwd(),
          options: { prompt: 'fixture', structuredOutput },
          outputSchema: jsonSchema(schema),
        },
        testInvocation(new AbortController().signal),
      ),
    ).rejects.toThrow(`(structuredOutput: "${structuredOutput}")`);
    await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  }
});

it('retains nullable optionals and strips null only from non-nullable optionals inside unions and records', () => {
  const schema = z.object({
    data: z.record(
      z.string(),
      z.discriminatedUnion('kind', [
        z.object({ kind: z.literal('a'), a: z.number().optional() }),
        z.object({ kind: z.literal('b'), b: z.string().nullable().optional() }),
      ]),
    ),
  });
  const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
  const decoded: unknown = JSON.parse(
    plan.decode(
      '{"data":[{"key":"x","value":{"kind":"b","b":null}},{"key":"y","value":{"kind":"a","a":null}}]}',
    ),
  );
  expect(decoded).toEqual({ data: { x: { kind: 'b', b: null }, y: { kind: 'a' } } });
  expect(schema.safeParse(decoded).success).toBe(true);
});

it('keeps partial enum-record keys optional while full enum records stay required', () => {
  const partial = z.partialRecord(z.enum(['a', 'b']), z.object({ n: z.number() }));
  const partialPlan = prepareCodexSchema(jsonSchema(partial), 'compat');
  const partialWire = partialPlan.schema as Record<string, unknown>;
  expect(partialWire['required']).toEqual(['a', 'b']);
  const partialProperties = partialWire['properties'] as Record<string, unknown>;
  for (const key of ['a', 'b']) {
    expect(partialProperties[key]).toMatchObject({ anyOf: [{ type: 'object' }, { type: 'null' }] });
  }
  const decoded: unknown = JSON.parse(partialPlan.decode('{"a":{"n":1},"b":null}'));
  expect(decoded).toEqual({ a: { n: 1 } });
  expect(partial.safeParse(decoded).success).toBe(true);

  const full = z.record(z.enum(['a', 'b']), z.object({ n: z.number() }));
  const fullPlan = prepareCodexSchema(jsonSchema(full), 'compat');
  const fullWire = fullPlan.schema as Record<string, unknown>;
  expect(fullWire['required']).toEqual(['a', 'b']);
  const fullProperties = fullWire['properties'] as Record<string, unknown>;
  for (const key of ['a', 'b']) {
    expect(fullProperties[key]).toMatchObject({ type: 'object' });
    expect(fullProperties[key]).not.toHaveProperty('anyOf');
  }
  expect(() => fullPlan.decode('{"a":{"n":1},"b":null}')).toThrow();
});

it('rejects a union of a record and an array whose wire encodings collide, in either order', () => {
  const record = z.record(z.string(), z.number());
  const pairs = z.array(z.object({ key: z.string(), value: z.number() }));
  for (const schema of [z.union([record, pairs]), z.union([pairs, record])]) {
    expect(() => prepareCodexSchema(jsonSchema(schema), 'compat')).toThrow(
      /Codex rejects this output schema \(structuredOutput: "compat"\):\n {2}\$ \(record-array-union\): .*wrap the variants in z\.object with a discriminator/u,
    );
  }
  // Nested unions, $ref-shared branches, and any array alternative (all of which accept `[]`) collide too.
  const nested = z.object({ data: z.union([z.string(), z.union([z.array(z.string()), record])]) });
  expect(() => prepareCodexSchema(jsonSchema(nested), 'compat')).toThrow(
    '$.data (record-array-union)',
  );
  const shared = {
    type: 'object',
    properties: { data: { anyOf: [{ $ref: '#/definitions/r' }, { $ref: '#/definitions/a' }] } },
    required: ['data'],
    additionalProperties: false,
    definitions: {
      r: {
        type: 'object',
        propertyNames: { type: 'string' },
        additionalProperties: { type: 'number' },
      },
      a: { type: 'array', items: { type: 'number' } },
    },
  };
  expect(() => prepareCodexSchema(shared, 'compat')).toThrow('$.data (record-array-union)');
});

it('decodes a union of two records by first match on the shared entries encoding', () => {
  const schema = z.object({
    data: z.union([z.record(z.string(), z.number()), z.record(z.string(), z.string())]),
  });
  const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
  for (const [wire, data] of [
    ['[{"key":"a","value":1}]', { a: 1 }],
    ['[{"key":"a","value":"x"}]', { a: 'x' }],
    ['[]', {}],
  ] as const) {
    const decoded: unknown = JSON.parse(plan.decode(`{"data":${wire}}`));
    expect(decoded).toEqual({ data });
    expect(schema.safeParse(decoded).success).toBe(true);
  }
});

it('supports shared and recursive local schema references', () => {
  const schema = {
    type: 'object',
    properties: { next: { anyOf: [{ $ref: '#' }, { type: 'null' }] }, name: { type: 'string' } },
    required: ['next'],
    additionalProperties: false,
  };
  expect(checkCodexSchema(schema).map((issue) => issue.path)).toEqual(['$.name']);
  const plan = prepareCodexSchema(schema, 'compat');
  expect(checkCodexSchema(plan.schema)).toEqual([]);
  expect(JSON.parse(plan.decode('{"next":{"next":null,"name":"child"},"name":null}'))).toEqual({
    next: { next: null, name: 'child' },
  });
  const shared = {
    type: 'object',
    properties: { 'odd/key': { $ref: '#/definitions/a~1b' } },
    required: ['odd/key'],
    additionalProperties: false,
    definitions: {
      'a/b': {
        type: 'object',
        properties: { value: { type: 'string' } },
        additionalProperties: false,
      },
    },
  };
  expect(checkCodexSchema(shared)[0]?.path).toBe('$["odd/key"].value');
  expect(
    JSON.parse(prepareCodexSchema(shared, 'compat').decode('{"odd/key":{"value":null}}')),
  ).toEqual({ 'odd/key': {} });
});

it('rejects invalid compatibility output instead of silently corrupting values', () => {
  const recordPlan = prepareCodexSchema(jsonSchema(z.record(z.string(), z.number())), 'compat');
  expect(() => recordPlan.decode('{}')).toThrow('missing value');
  expect(() => recordPlan.decode('{"value":{}}')).toThrow('array of key/value');
  expect(() => recordPlan.decode('{"value":[{}]}')).toThrow('requires key and value');
  expect(() =>
    recordPlan.decode('{"value":[{"key":"x","value":1},{"key":"x","value":2}]}'),
  ).toThrow('duplicate keys');
  const decoded: unknown = JSON.parse(
    recordPlan.decode('{"value":[{"key":"__proto__","value":1}]}'),
  );
  expect(Object.getPrototypeOf(decoded)).toBe(Object.prototype);
  expect(Object.hasOwn(decoded as object, '__proto__')).toBe(true);
  expect(() =>
    prepareCodexSchema(jsonSchema(z.array(z.string())), 'compat').decode('{"value":null}'),
  ).toThrow('must be an array');
  expect(() => prepareCodexSchema(jsonSchema(z.object({})), 'compat').decode('null')).toThrow(
    'must be an object',
  );
  expect(() =>
    prepareCodexSchema(
      jsonSchema(z.union([z.object({ a: z.string() }), z.object({ b: z.number() })])),
      'compat',
    ).decode('{"value":{}}'),
  ).toThrow('did not match any');
});

it('preserves original validation and refuses tuples in compatibility mode before spawning', async () => {
  const { binary, directory, marker } = await binaryFor({ value: 'x' });
  await expect(
    new CliHarness({ codexBinary: binary }).invoke(
      {
        harness: 'codex',
        cwd: process.cwd(),
        options: { prompt: 'fixture' },
        outputSchema: jsonSchema(z.tuple([z.string()])),
      },
      testInvocation(new AbortController().signal),
    ),
  ).rejects.toThrow('(tuple)');
  await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  const schema = z.object({ value: z.string().refine((value) => value.length > 3, 'too short') });
  const workflow = defineWorkflow({
    name: 'refinement',
    version: '1',
    input: z.null(),
    output: schema,
    async run(ctx) {
      return (await ctx.codex.object('answer', { prompt: 'fixture', schema })).output;
    },
  });
  await expect(
    runWorkflow(workflow, {
      runId: 'refine',
      stateDir: directory,
      input: null,
      harness: new CliHarness({ codexBinary: binary }),
    }),
  ).rejects.toThrow('too short');
});

it('does not mutate the supplied schema and leaves strict native schemas unchanged', () => {
  const schema = jsonSchema(z.object({ name: z.string() }));
  const copy = structuredClone(schema);
  const strict = prepareCodexSchema(schema, 'strict');
  expect(strict.schema).toEqual(schema);
  expect(strict.decode('original bytes')).toBe('original bytes');
  prepareCodexSchema(schema, 'compat');
  expect(schema).toEqual(copy);
  expect(() => checkCodexSchema({ $ref: 'https://example.test/schema' })).toThrow('external');
  expect(() => checkCodexSchema({ $ref: '#/definitions/missing' })).toThrow('Unresolved');
  expect(() => checkCodexSchema({ $ref: '#' })).toThrow('Cyclic schema reference');
  expect(
    checkCodexSchema({
      $ref: '#/anyOf/0',
      anyOf: [{ type: 'object', properties: {}, required: [], additionalProperties: false }],
    }),
  ).toEqual([]);
  const described = prepareCodexSchema(
    jsonSchema(z.record(z.string(), z.string()).describe('Labels by ID')),
    'compat',
  );
  expect(described.schema).toMatchObject({
    properties: { value: { description: 'Labels by ID' } },
  });
});

it('rejects boolean root schemas instead of skipping the root check', () => {
  const issue = {
    path: '$',
    rule: 'object-root',
    fix: 'Wrap the root in z.object({ value: ... }), or use structuredOutput: "compat".',
  };
  expect(checkCodexSchema(false)).toEqual([issue]);
  // `true` is `{}`: it also accepts any value, so it is untyped as well as not an object.
  expect(checkCodexSchema(true).map(({ path, rule }) => ({ path, rule }))).toEqual([
    { path: '$', rule: 'object-root' },
    { path: '$', rule: 'untyped' },
  ]);
  expect(() => prepareCodexSchema(false, 'strict')).toThrow('object-root');
  // `false` can never be satisfied on the wire (compat has no way to encode "always invalid"),
  // so it must be rejected locally rather than compiled into an unrestricted `{ value: {} }`.
  expect(() => prepareCodexSchema(false, 'compat')).toThrow('always fails validation');
  // `true` has no concrete wire type, so compat rejects it like z.unknown() instead of wrapping it.
  expect(() => prepareCodexSchema(true, 'compat')).toThrow('$ (untyped)');
});

const untypedAt = (schema: z.ZodType | ReturnType<typeof jsonValue>): string[] =>
  checkCodexSchema(schema)
    .filter((issue) => issue.rule === 'untyped')
    .map((issue) => issue.path);

it('flags type-less subschemas at the path of the offending value', () => {
  expect(untypedAt(z.object({ a: z.unknown() }))).toEqual(['$.a']);
  expect(untypedAt(z.object({ a: z.array(z.unknown()) }))).toEqual(['$.a.items']);
  expect(untypedAt(z.object({ a: z.unknown().nullable() }))).toEqual(['$.a.anyOf[0]']);
  expect(untypedAt(z.object({ a: z.unknown().describe('anything') }))).toEqual(['$.a']);
  expect(untypedAt(z.object({ a: z.never() }))).toEqual(['$.a']);
  expect(untypedAt(z.unknown())).toEqual(['$']);
  expect(
    checkCodexSchema(z.object({ a: z.unknown().optional() })).map(({ path, rule }) => ({
      path,
      rule,
    })),
  ).toEqual([
    { path: '$.a', rule: 'optional' },
    { path: '$.a', rule: 'untyped' },
  ]);
  expect(untypedAt({ type: 'object', properties: { a: true }, required: ['a'] })).toEqual(['$.a']);
  const issue = checkCodexSchema(z.object({ a: z.unknown() }))[0];
  expect(issue?.fix).toContain('concrete type');
  expect(issue?.fix).toContain('z.string()');
});

it('judges a $ref by its target and checks shared definitions once per use', () => {
  const shared = z.unknown();
  expect(untypedAt(z.object({ a: shared, b: shared }))).toEqual(['$.a', '$.b']);
  expect(untypedAt({ $defs: { t: { type: 'string' } }, $ref: '#/$defs/t' })).toEqual([]);
});

it('does not flag enum-only nodes, z.json() or loose objects', () => {
  expect(untypedAt(z.object({ a: z.literal(['x', 1]) }))).toEqual([]);
  expect(untypedAt(z.object({ a: z.json() }))).toEqual([]);
  const loose = z.looseObject({ a: z.string() });
  expect(checkCodexSchema(loose).map((issue) => issue.rule)).toEqual(['open-object']);
  const catchall = z.object({ a: z.string() }).catchall(z.unknown());
  expect(checkCodexSchema(catchall).map((issue) => issue.rule)).toEqual(['open-object']);
  const nested = z.object({ a: z.string() }).catchall(z.object({ x: z.unknown() }));
  expect(untypedAt(nested)).toEqual([]);
  // A shared definition is still checked on its own.
  expect(
    untypedAt({
      type: 'object',
      properties: {},
      additionalProperties: { type: 'object', additionalProperties: {} },
      $defs: { loose: {} },
    }),
  ).toEqual(['$.$defs.loose']);
});

it('rejects untyped values in compat with the original path and no compat remedy', () => {
  const cases: [z.ZodType, string][] = [
    [z.object({ a: z.unknown() }), '$.a (untyped)'],
    [z.object({ a: z.array(z.any()) }), '$.a.items (untyped)'],
    [z.object({ a: z.unknown().nullable() }), '$.a.anyOf[0] (untyped)'],
    [z.record(z.string(), z.unknown()), '$.additionalProperties (untyped)'],
    [z.record(z.enum(['a']), z.unknown()), '$.additionalProperties (untyped)'],
    [z.partialRecord(z.enum(['a']), z.unknown()), '$.additionalProperties (untyped)'],
    [z.unknown(), '$ (untyped)'],
  ];
  for (const [schema, path] of cases) {
    let message = '';
    try {
      prepareCodexSchema(jsonSchema(schema), 'compat');
    } catch (error) {
      message = (error as Error).message;
    }
    expect(message).toContain('Codex rejects this output schema (structuredOutput: "compat"):');
    expect(message).toContain(path);
    expect(message).toContain('concrete type');
    expect(message).not.toContain('or use structuredOutput');
    expect(message).not.toMatch(/\$\.value\b/u);
  }
});

it('keeps the untyped fix for a value inside an unmerged intersection', () => {
  const schema = z.intersection(z.object({ a: z.unknown() }), z.record(z.string(), z.unknown()));
  const json = jsonSchema(schema);
  expect(JSON.stringify(json)).toContain('allOf');
  let message = '';
  try {
    prepareCodexSchema(json, 'compat');
  } catch (error) {
    message = (error as Error).message;
  }
  expect(message).toContain('(untyped)');
  expect(message).toContain('concrete type');
  expect(message).not.toContain('z.intersection');
});

it('still closes loose and catchall objects in compat', () => {
  for (const schema of [
    z.looseObject({ a: z.string() }),
    z.object({ a: z.string() }).catchall(z.unknown()),
    z.object({ a: z.string() }).catchall(z.object({ x: z.unknown() })),
    // A meta id moves the discarded catchall value into `definitions`, which compat never sends.
    z.object({ a: z.string() }).catchall(z.unknown().meta({ id: 'anything' })),
  ]) {
    const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
    expect(plan.schema).toMatchObject({ additionalProperties: false });
    expect(checkCodexSchema(plan.schema)).toEqual([]);
  }
});

it('does not reject untyped or tuple nodes in definitions compat never sends', () => {
  for (const loose of [{}, { type: 'array', items: [{ type: 'string' }] }]) {
    const schema = {
      type: 'object',
      properties: {},
      required: [],
      additionalProperties: false,
      $defs: { loose },
    };
    expect(checkCodexSchema(schema).map((issue) => issue.path)).toContain('$.$defs.loose');
    expect(() => prepareCodexSchema(schema, 'compat')).not.toThrow();
  }
  const untypedDefinition = {
    type: 'object',
    properties: {},
    required: [],
    additionalProperties: false,
    $defs: { loose: {} },
  };
  expect(() => prepareCodexSchema(untypedDefinition, 'strict')).toThrow('$.$defs.loose (untyped)');
  // A reachable definition is still reported at its use site.
  const reachable = {
    type: 'object',
    properties: { a: { $ref: '#/$defs/loose' } },
    required: ['a'],
    additionalProperties: false,
    $defs: { loose: {} },
  };
  expect(() => prepareCodexSchema(reachable, 'compat')).toThrow('$.a (untyped)');
});

it('labels rejections with the active structuredOutput mode and drops compat-only hints', () => {
  const tupleSchema = jsonSchema(z.tuple([z.string()]));
  expect(() => prepareCodexSchema(tupleSchema, 'strict')).toThrow(
    'Codex rejects this output schema (structuredOutput: "strict"):',
  );
  expect(() => prepareCodexSchema(tupleSchema, 'compat')).toThrow(
    'Codex rejects this output schema (structuredOutput: "compat"):',
  );
  // A type array like `["object", "null"]` still bypasses compat's object transform (tracked
  // separately), so its optional property survives to the final wire check. That makes it a
  // convenient way to exercise a non-tuple rejection surfacing from compat mode.
  const nullableObjectSchema = {
    type: 'object',
    properties: {
      nested: { type: ['object', 'null'], properties: { name: { type: 'string' } } },
    },
    required: ['nested'],
    additionalProperties: false,
  };
  let message = '';
  try {
    prepareCodexSchema(nullableObjectSchema, 'compat');
    expect.fail('expected prepareCodexSchema to throw');
  } catch (error) {
    message = (error as Error).message;
  }
  expect(message).toContain('Codex rejects this output schema (structuredOutput: "compat"):');
  expect(message).toContain(
    '$.nested.name (optional): Make this property required and .nullable().',
  );
  expect(message).not.toContain('or use structuredOutput');
});

it('adapts an object-with-object intersection with an optional field in compat mode', () => {
  // z.toJSONSchema flattens an intersection of two object schemas into one closed object (Zod 4.5.4),
  // even when a branch has an optional property, so this never reaches the `allOf` compiler path.
  const schema = z.intersection(
    z.object({ a: z.string().optional() }),
    z.object({ b: z.number() }),
  );
  const plan = prepareCodexSchema(jsonSchema(schema), 'compat');
  expect(JSON.parse(plan.decode('{"a":null,"b":1}'))).toEqual({ b: 1 });
  expect(JSON.parse(plan.decode('{"a":"x","b":1}'))).toEqual({ a: 'x', b: 1 });
});

it('rejects an object-and-record intersection in compat mode with an intersection-specific fix', () => {
  // z.toJSONSchema cannot merge an object branch with a record branch, so this survives as `allOf`.
  // Adapting each branch separately would close the object (dropping the record's extra keys) or
  // turn the record into an array (breaking the object branch), so compat must reject it outright.
  const schema = z.intersection(z.object({ a: z.string() }), z.record(z.string(), z.number()));
  let message = '';
  try {
    prepareCodexSchema(jsonSchema(schema), 'compat');
    expect.fail('expected prepareCodexSchema to throw');
  } catch (error) {
    message = (error as Error).message;
  }
  expect(message).toContain('Codex rejects this output schema (structuredOutput: "compat"):');
  expect(message).toContain(
    '(record): structuredOutput: "compat" cannot adapt shapes inside z.intersection (allOf)',
  );
  expect(message).not.toContain('structuredOutput: "compat" for records');
});

it.each(['discriminated-union', 'array-root', 'string-root'])(
  'rejects the observed Claude %s root before spawning',
  async (name) => {
    const entry = schemaMatrix.find((entry) => entry.name === name);
    if (!entry) throw new Error('Missing matrix entry');
    const { binary, marker } = await binaryFor({});
    await expect(
      new CliHarness({ claudeBinary: binary }).invoke(
        {
          harness: 'claude',
          cwd: process.cwd(),
          options: { prompt: 'fixture' },
          outputSchema: jsonSchema(entry.schema),
        },
        testInvocation(new AbortController().signal),
      ),
    ).rejects.toThrow('Claude structured output requires an object root at $');
    await expect(stat(marker)).rejects.toMatchObject({ code: 'ENOENT' });
  },
);

it.each(
  schemaMatrix.filter(
    (entry) => !['discriminated-union', 'array-root', 'string-root'].includes(entry.name),
  ),
)('keeps the original $name schema for Claude', async ({ schema, output }) => {
  const { binary, directory } = await binaryFor({});
  const schemaPath = join(directory, 'claude-schema.json');
  await writeFile(
    binary,
    `#!${process.execPath}\nconst fs = require('node:fs'); const args = process.argv.slice(2); fs.writeFileSync(${JSON.stringify(schemaPath)}, args[args.indexOf('--json-schema') + 1]); console.log(${JSON.stringify(JSON.stringify({ type: 'result', subtype: 'success', structured_output: output }))});`,
  );
  const response = await new CliHarness({ claudeBinary: binary }).invoke(
    {
      harness: 'claude',
      cwd: process.cwd(),
      options: { prompt: 'fixture' },
      outputSchema: jsonSchema(schema),
    },
    testInvocation(new AbortController().signal),
  );
  expect(JSON.parse(await readFile(schemaPath, 'utf8'))).toEqual(jsonSchema(schema));
  expect(schema.safeParse(JSON.parse(response.text)).success).toBe(true);
});
